### ISSUE TITLE
What MacOS Sierra driver for NodeMCU v1.0 12e DevKit v0.9 whould you suggest to use ?

### ISSUE THREAD

**Issue by viatsyshyn** [dev1lmini/Home-KIT#1]

**Comment by viatsyshyn** [comment]
fixed grammar

**Comment by viatsyshyn** [comment]
https://blog.sengotta.net/signed-mac-os-driver-for-winchiphead-ch340-serial-bridge/ this blog post's driver resolves MacOS kernel panic!

**Comment by kuzemkon** [comment]
Hi, @viatsyshyn, thank you for your question and answer. Are you resolve your problem?

**Comment by viatsyshyn** [comment]
Yes, with the help of driver from https://blog.sengotta.net/signed-mac-os-driver-for-winchiphead-ch340-serial-bridge/
